version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "setting up functions..."
      - | 
        does_lambda_exist() {
          aws lambda get-function --function-name $1 > /dev/null 2>&1
          if [ 0 -eq $? ]; then
            echo "Lambda '$1' exists"
          else
            echo "Lambda '$1' does not exist"
          fi
        }
      - test = (does_lambda_exist github-to-lambda)
  build:
    commands:
      - echo "Looking for all lambda functions..."
      - |
        cd lambdas
        pwd
        for function in */ ; do
          echo ${function%/}
          cd ${function}

          if [ -f "index.js" ]; then
            exists=$(does_lambda_exist my_lambda_fn_name) 
            if [ $exists -eq 0 ]; then
              echo "Compiling code to single file for ${function%/} lambda function..."
              npx ncc build index.js

              echo "Zipping ${function%/} handler code..."
              zip -j deploy.zip ./dist/*

              echo "Deploying Lambda"
              aws lambda update-function-code --function-name=${function%/} --zip-file=fileb://deploy.zip

              echo "Deployed ${function%/}"
            else
              echo "Lambda ${function%/} DOES NOT exist"
            fi
            
          fi

          cd ..
        done