version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - git fetch --unshallow 
      - git fetch origin 
  build:
    commands:
      - echo "Looking for all lambda functions..."
      - |
        export CODEBUILD=true
        cd lambdas
        pwd
        for function in */ ; do
          echo ${function%/}
          cd ${function}

          if [ -f "index.js" ]; then
            aws lambda get-function --function-name=${function%/} > /dev/null 2>&1
            status=$?
            echo $status
            if [ $status -eq 0 ]; then
              echo "Lambda '${function%/} ' exists"      
              if [ "$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_WEBHOOK_PREV_COMMIT | grep -e ${function%/})" != "" ]; then
                echo "Compiling code to single file for ${function%/} lambda function..."
                npx ncc build index.js

                echo "Zipping ${function%/} handler code..."
                zip -j deploy.zip ./dist/*

                echo "Updating Lambda"
                aws lambda update-function-code --function-name=${function%/} --zip-file=fileb://deploy.zip

                echo "Deployed ${function%/}"
              else
                echo 'Skipping... (Code was not updated)'
              fi
              
            else
              echo "Lambda ${function%/} DOES NOT exist"
              echo "Compiling code to single file for ${function%/} lambda function..."
              npx ncc build index.js

              echo "Zipping ${function%/} handler code..."
              zip -j deploy.zip ./dist/*

              echo "Creating Lambda role"
              role_arn=$(aws iam create-role --role-name ${function%/}-default-role --assume-role-policy-document file://defaultRole.json --query 'Role.Arn' --output text)
              sleep 5
              echo "Attaching default policy Lambda role"
              aws iam attach-role-policy  --role-name ${function%/}-default-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
              sleep 5
              echo "Creating Lambda function"
              aws lambda create-function --function-name=${function%/} --role ${role_arn} --runtime nodejs22.x --handler index.handler --zip-file fileb://deploy.zip
              echo "Lambda has been created!"
            fi
          fi

          cd ..
        done