version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Looking for all lambda functions..."
      - |
        cd lambdas
        pwd
        for function in */ ; do
          echo ${function}
          cd ${function}

          if [ -f "index.js" ]; then
            echo "Compiling code to single file for ${function} lambda function..."
            npx ncc build index.js

            echo "Zipping ${function} handler code..."
            zip -j deploy.zip ./dist/*

            echo "Deploying Lambda"
            aws lambda update-function-code --function-name=${function} --zip-file=fileb://deploy.zip

            echo "Deployed ${function}"
          fi

          cd ..
        done